language: java

jdk:
  - openjdk6
  - oraclejdk6
  - openjdk7
  - oraclejdk7
  - openjdk8
  - oraclejdk8

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e5c7c3a73b34ad93d29b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
